### ISSUE TITLE
AUR package missing dependencies

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/Rofi_MPD#14]
Since restructuring the package the AUR package will no longer install. I do not use Arch any more so I'm unable to test this. If anybody can update it that'd be great; it should only be changing a couple of paths.

**Comment by JakeStanger** [comment]
Hey @rubdos I'm looking to get this packaged up for a few distros so found the time to test this. Could you update the dependencies section of the PKGBUILD please as follows:

```makepkg
makedepends=('git' 'binutils' 'python-setuptools' 'fakeroot')
depends=('python' 'python-mpd2' 'python-mutagen' 'rofi')
```

Everything else should still be good :)

**Comment by rubdos** [comment]
Isn't `binutils` assumed when you're building with `makepkg`? Otherwise, lgtm. EDIT: I've included it for now, since I'm not sure.

**Comment by rubdos** [comment]
I've pushed a new version. Feel free to ping me here any time you have AUR issues; I didn't even notice this! :o

**Comment by JakeStanger** [comment]
Not sure whether it is. I ran `makepkg` on a blank Arch VM and `binutils` was missing so it makes sense to include it in my eyes.

Thanks a bunch :)

**Comment by rubdos** [comment]
> Thanks a bunch :)

No problem. Don't forget to close the issue :-)

**Comment by JakeStanger** [comment]
Sorry @rubdos the package is still showing as last updated March. Are you able to confirm this? Once I know for sure it's updated I'll close the issue.

**Comment by rubdos** [comment]
Woops, forgot to `git push`...

**Comment by JakeStanger** [comment]
No problem, thanks for updating it!
